### ISSUE TITLE
Installing fails?

### ISSUE THREAD

**Issue by aleclarson** [vincentsaluzzo/node-microphone#5]
``` sh
sudo npm i --save microphone
```

Results in this output:

``` sh
> lame@1.0.3 install /Users/aleclarsoniv/dev/projects/vocus/node_modules/microphone/node_modules/lame
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/Users/aleclarsoniv/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:166:7)
gyp ERR! stack     at Request.onRequestResponse (/Users/aleclarsoniv/lib/node_modules/npm/node_modules/request/request.js:1176:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:166:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:410:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:300:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "/Users/aleclarsoniv/bin/iojs" "/Users/aleclarsoniv/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/aleclarsoniv/dev/projects/vocus/node_modules/microphone/node_modules/lame
gyp ERR! node -v v1.6.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.1.0
npm ERR! argv "/Users/aleclarsoniv/bin/iojs" "/Users/aleclarsoniv/bin/npm" "i" "--save" "microphone"
npm ERR! node v1.6.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! lame@1.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lame@1.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the lame package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls lame
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aleclarsoniv/dev/projects/vocus/npm-debug.log
```

Do you have any experience with this error?

Do you want me to paste the text in `npm-debug.log`?

Thanks.

**Comment by aleclarson** [comment]
Hmm. This seems to be a duplicate of [node-lame#42](https://github.com/TooTallNate/node-lame/issues/42).

Guess I'll use Node.js then!
